#! config.yml

#@ load("@ytt:data", "data")
#@ load("labels.lib.yml", "labels")
#@ load("format.star", "fmt")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ fmt(data.values.name, "deployment")
  namespace: #@ data.values.namespace
  labels: #@ labels(data.values.name, data.values.version)
spec:
  selector:
    matchLabels:
      app: #@ data.values.name
  replicas: #@ data.values.replicas
  template:
    spec:
      containers:
        - name:  #@ data.values.name
          image: index.docker.io/k14s/image@sha256:6ab29951e0207fde6760f6db227f218f20e875f45b22e8ca0ee06c0c8cab32cd
---
apiVersion: v1
kind: Service
metadata:
  name: #@ fmt(data.values.name, "service")
  labels: #@ labels(data.values.name, data.values.version)
spec:
  type: ClusterIP
  ports:
    - port: 80