#! schema.yml
#@data/values-schema
---
name: "frontend"     #! ensures that any value for 'frontend' must be a string
namespace: "default" #! ensures that any value for 'default' must be a string
version: "0.1.0"     #! ensures that any value for 'version' must be a string
replicas: 1          #! ensures that any value for 'replicas' must be a int