apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: hipster-store 
  namespace: hipster-cluster
spec:
  topology:
    controlPlane:
      count: 1
      class: best-effort-xsmall
      storageClass: k8s-policy
    workers:
      count: 3
      class: best-effort-xsmall
      storageClass: k8s-policy
  distribution:
    version: v1.17.8+vmware.1-tkg.1.5417466
  settings:
    network:
      cni:
        name: antrea
      services:
        cidrBlocks: ["198.64.100.0/12"]
      pods:
        cidrBlocks: ["192.1.2.0/16"]
      serviceDomain: managedcluster.local
