apiVersion: installers.tmc.cloud.vmware.com/v1alpha1
kind: AgentInstall
metadata:
  name: tmc-agent-installer-config
  namespace: svc-tmc-c8
spec:
  operation: INSTALL
  registrationLink: https://tanzuendtoend.tmc.cloud.vmware.com/installer?id=686b3c303d138e6ef8869e7087c88933e37f14ee5e51f4116d6704dcb43d7f50&source=registration
