apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fa-app
  name: fa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fa-app
  template:
    metadata:
      labels:
        app: fa-app
    spec:
      containers:
      - image: arn.ocir.io/axu4exjufej2/mattiassoderberj/fa-app/fa-app:0.8-arm64
        imagePullPolicy: Always
        name: fa-app
        securityContext:
          allowPrivilegeEscalation: true
          runAsNonRoot: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
      imagePullSecrets:
        - name: fa-app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: fa-app-svc
  labels:
    name: fa-app-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: fa-app
  type: LoadBalancer
