apiVersion: v1
kind: Service
metadata:
  name: cbp-demo-svc
  labels:
    name: cbp-demo-svc
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: cbp-demo
  type: LoadBalancer
