apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: rmq-clu
spec:
  topology:
    controlPlane:
      replicas: 1
      storageClass: vsphere-with-tanzu-storage-policy
      tkr:
        reference:
          name: v1.23.8---vmware.3-tkg.1
      vmClass: best-effort-medium
    nodePools:
    - name: worker-nodepool-a1
      replicas: 3
      storageClass: vsphere-with-tanzu-storage-policy
      tkr:
        reference:
          name: v1.23.8---vmware.3-tkg.1
      vmClass: best-effort-large
