apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: advania-clu
spec:
  topology:
    controlPlane:
      replicas: 1
      storageClass: vc01cl01-t0compute
      tkr:
        reference:
          name: v1.23.8---vmware.3-tkg.1
      vmClass: best-effort-small
    nodePools:
    - name: worker-nodepool-a1
      replicas: 2
      storageClass: vc01cl01-t0compute
      tkr:
        reference:
          name: v1.23.8---vmware.3-tkg.1
      vmClass: best-effort-large
