#! schema.yml

#@ load("@ytt:assert", "assert")

#@data/values-schema
---
#@schema/validation one_of=["frontend", "backend"]
name: "frontend"
#@schema/validation ("namespace can't be blank", assert.min_len(1))     
namespace: "default" 
version: "0.1.0"    
#@schema/validation min=1,max=5
replicas: 1        
