apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: vc01cl01-t0compute
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

