apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cbp-demo
  name: cbp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cbp-demo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cbp-demo
    spec:
      containers:
      - image: registry.tanzu.dk/app-images/tbs-demo-app:b1.20231201.075350
        name: cbp-demo
        securityContext:
          allowPrivilegeEscalation: true
          runAsNonRoot: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: cbp-demo-svc
  labels:
    name: cbp-demo-svc
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: cbp-demo
  type: LoadBalancer
