kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-admin
  namespace: demo
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-binding
  namespace: demo
subjects:
  - kind: ServiceAccount
    name: demo-account
    namespace: demo
roleRef:
  kind: Role
  name: demo-admin
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-binding
  namespace: demo
subjects:
  - kind: ServiceAccount
    name: default
    namespace: demo
roleRef:
  kind: Role
  name: default-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-role
  namespace: demo
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs: ["get","list","watch"]
  - apiGroups:
    - ""
    resources:
    - pods/exec
    verbs:
    - create
