apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: production-clu
spec:
  topology:
    controlPlane:
      replicas: 3
      storageClass: vc01cl01-t0compute
      tkr:
        reference:
          name: v1.23.8---vmware.3-tkg.1
      vmClass: best-effort-medium
    nodePools:
    - name: worker-nodepool-a1
      replicas: 10
      storageClass: vc01cl01-t0compute
      tkr:
        reference:
          name: v1.23.8---vmware.3-tkg.1
      vmClass: best-effort-large
