apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: mattias-db-instance
  namespace: pg-db
spec:
  storageClassName: vc01cl01-t0compute
  storageSize: 2Gi
  sharedMemorySize: 800Mi
  monitorStorageClassName: vc01cl01-t0compute
  monitorStorageSize: 1G
  resources:
    monitor:
      limits:
        cpu: 800m
        memory: 800Mi
      requests:
        cpu: 800m
        memory: 800Mi
    metrics:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
  pgConfig:
    dbname: spring-music
    username: pgadmin
  postgresVersion:
    name: postgres-15 # View available versions with `kubectl get postgresversion`
  serviceType: LoadBalancer
  imagePullSecret:
    name: regsecret
# highAvailability:
#   enabled: true
# logLevel: Debug
# backupLocation:
#   name: backuplocation-sample
# certificateSecretName:
